# Generated by Django 6.0.3 on 2026-05-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_alter_comment_article"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(),
        ),
    ]
