# Generated by Django 6.0.3 on 2026-04-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.ImageField(upload_to="courses/"),
        ),
    ]
