# Generated by Django 6.0.3 on 2026-04-03 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("surnames", models.CharField(max_length=100)),
                ("number", models.CharField(max_length=10)),
                ("mail", models.CharField(max_length=50)),
                ("page_link", models.URLField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="degree",
            name="type",
        ),
        migrations.AddField(
            model_name="degree",
            name="description",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="degree",
            name="tipo",
            field=models.CharField(
                choices=[("L", "Bachelor"), ("M", "Master")], null=True
            ),
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=1000)),
                ("program", models.CharField(max_length=1000)),
                ("ects", models.IntegerField()),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "year",
                    models.IntegerField(
                        choices=[(1, "First"), (2, "Second"), (3, "Third")]
                    ),
                ),
                ("image", models.ImageField(upload_to="portfolio/fotos")),
                (
                    "degree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="portfolio.degree",
                    ),
                ),
                (
                    "professors",
                    models.ManyToManyField(
                        related_name="subjects", to="portfolio.professor"
                    ),
                ),
            ],
        ),
    ]
