# Generated by Django 6.0.3 on 2026-04-03 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_competence_education_language_makingof_project_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tfc",
            name="counselor",
        ),
    ]
