# Generated by Django 6.0.3 on 2026-04-03 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_remove_tfc_counselor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="professor",
            name="number",
        ),
    ]
