# Generated by Django 6.0.3 on 2026-04-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_alter_language_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="technlogies",
            field=models.ManyToManyField(
                related_name="projects", to="portfolio.technology"
            ),
        ),
    ]
