# Generated by Django 6.0.3 on 2026-04-25 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_project_technlogies"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="technlogies",
            new_name="technologies",
        ),
    ]
