# Generated by Django 6.0.5 on 2026-05-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_rename_technlogies_project_technologies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tfc",
            name="description",
            field=models.TextField(),
        ),
    ]
