# Generated by Django 6.0.5 on 2026-05-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0009_alter_tfc_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tfc",
            name="author",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="title",
            field=models.CharField(max_length=1000),
        ),
    ]
