# Generated by Django 6.0.3 on 2026-03-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="users",
        ),
        migrations.AddField(
            model_name="user",
            name="favorites",
            field=models.ManyToManyField(related_name="users", to="recipes.recipe"),
        ),
    ]
